data:
  processed_dir: "data/processed"
  subject: "A"          
  val_split: 0.15

model:
  spatial_kernels: 10
  temporal_kernels: 50
  temporal_kernel_width: 13
  temporal_stride: 13
  lstm_hidden: 128
  lstm_layers: 1
  bidirectional: True
  bayes_fc_hidden: 100

bayes:
  prior_sigma1: 0.1
  prior_sigma2: 0.0005
  prior_pi: 0.5
  init_std: 0.05

train:
  batch_size_per_step: 16
  accumulate_steps: 7
  n_mc_train: 1
  n_mc_test_debug: 30
  epochs: 60
  lr: 0.0003
  optimizer: Adam
  fp16: true
  seed: 42
  num_workers: 0

save_dir: results_A
